//1. Named credentials
//2 create password authentication view
//3. edit each one
//A. URL add test.
//B. Authentication Protocol: No Authentication

//the following script replaces 15_Named_Credentials_Update which used an Apex script


Run "Environment_Refresh/EnvRefresh_Helpers".Search_Setup "Named Credentials", "Environment_Refresh/Sandbox_Post_Refresh_Steps/07_CARMA_Post_Refresh_Steps/Navigation_Links/NamedCredentials", "Environment_Refresh/Sandbox_Post_Refresh_Steps/Navigation_Links/Step_Headers/NamedCredentials"


Put ResourcePath("Refresh_Reports\"&the suitevariables.SandboxName&"_Refresh_Report"&".csv") into Refresh_Report
open file Refresh_Report for appending
write return&"15_Named_Credentials_Manual_Masking"& return to file Refresh_Report
write "Updating named credentials using manual masking." & return to file Refresh_Report


put the MultipleFoundAction into MultipleFoundState
set the MultipleFoundAction to UseFirstLocation

Set SelectedView to "Environment_Refresh/Sandbox_Post_Refresh_Steps/04_Generic_Refresh_Steps/15_Named_Credentials_Manual_Masking/PasswordAuthentication_SelectedView"
Set DesiredView to "Environment_Refresh/Sandbox_Post_Refresh_Steps/04_Generic_Refresh_Steps/15_Named_Credentials_Manual_Masking/PasswordAuthentication_DesiredView"
Set ViewName to "Password Authentication"
Set MakeMyView to true
Set FilterBoolean to true
Set FieldFilterVar to "Authentication Protocol"
Set FieldOperatorVar to "equals"
Set FieldValueVar to "Password Authentication"
Run "Utilities/CustomView".ChangeMyView SelectedView, DesiredView, ViewName, MakeMyView, FilterBoolean, FieldFilterVar, FieldOperatorVar, FieldValueVar

typetext controlkey, "lc"
put the remoteclipboard into NamedCredURL
repeat until not imagefound(image:"Environment_Refresh/Sandbox_Post_Refresh_Steps/04_Generic_Refresh_Steps/15_Named_Credentials_Manual_Masking/EditDel_HotspotEdit",waitfor:3)
	Log "Found a Named Credential URL to change."
	repeat at least once until imagefound("Environment_Refresh/Sandbox_Post_Refresh_Steps/04_Generic_Refresh_Steps/09_Custom_Links/Save")
		click foundimagelocation()
	end repeat
	
	//Winter '23 release broke the below.
	(*
	repeat until not imagefound("Environment_Refresh/Sandbox_Post_Refresh_Steps/04_Generic_Refresh_Steps/15_Named_Credentials_Manual_Masking/Edit_Delete_Blue")
		Log "Found a Named Credential URL to change."
		put y of foundimagelocation() into RowY
		put x of imagelocation("Environment_Refresh/Sandbox_Post_Refresh_Steps/04_Generic_Refresh_Steps/15_Named_Credentials_Manual_Masking/Label_LinkBelowIt") into RowX
		//clicking the link too soon here.
		Repeat at least once until imagefound("Environment_Refresh/Sandbox_Post_Refresh_Steps/04_Generic_Refresh_Steps/09_Custom_Links/Save")
			click [RowX,RowY]
			if imagefound(image:"Environment_Refresh/Sandbox_Post_Refresh_Steps/04_Generic_Refresh_Steps/09_Custom_Links/Edit",waitfor:6)
			then
				click foundimagelocation()
			end if
			if the repeatindex > 10 then throw "Could not find Save button."
		End Repeat
		*)
	
	typetext controlkey,"c"
	put the remoteclipboard
	
	click "Environment_Refresh/Sandbox_Post_Refresh_Steps/06_WH_Hotline_For_Refresh/07_MPIE_Setup/URL_Field"
	typetext controlkey,"a","c"
	set URLTmp to remoteclipboard()
	set OldURL to URLTmp 
	////////////////////////////////////////////////////////////////////////////////////////
	//replace "salesforce" in URLTmp with "test.salesforce"
	////////////////////////////////////////////////////////////////////////////////////////
	/////////New URL name per Chelsea on 3/9/22//////////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////
	if URLTmp contains ...
		"salesforce.lighthouse.va.gov" : Replace "salesforce.lighthouse.va.gov" in URLTmp with "test-salesforce.lighthouse.va.gov"
		"awsgc.dip.va.gov" : Replace "awsgc.dip.va.gov" in URLTmp with "qa-salesforce.dip.va.gov"
		"casemgmt.mbms.va.gov" : Replace "casemgmt.mbms.va.gov" in URLTmp with "casemgmt.training.mbms.va.gov"
		"soa.valerir.services.lgy.va.gov" : Replace "soa.valerir.services.lgy.va.gov" in URLTmp with "soa.valerir.services.lgy.va.gov"
		"api.va.gov" : Replace "api.va.gov" in URLTmp with SandboxName&"-api.va.gov"
		"int-salesforce.dip.va.gov" : replace "int" in URLTmp with "qa"
		else
			beep
			Ask "URL found:" with URLTmp title "Do you wish to input a custom URL?" message "URL does not contain any of the strings that the script has been told to modify. Script has been instructed to stop if this is the case. Update the URL and click OK to enter a custom URL, or just hit OK without editing to simply skip this one."
			replace " " in it with ""
			set URLTmp to it
	end if	
	SetRemoteClipboard URLTmp
	typetext controlkey,"v"	
	Log "Found URL......:"&&OldURL
	Log "Updated URL...:"&&URLTmp
	
	
	
	(*
		SandboxName&"-api.va.gov" : Log "api url already updated with sandbox"
		else if URLTmp contains...
			"test-salesforce.lighthouse.va.gov" : Log "salesforce.lighthouse url already updated with sandbox"
			else if URLTmp contains ...
	Log "updating Named Credential info for:"&&remoteclipboard()
	replace "awsgc" in URLTmp with "qa-awsgc"
	Log "New URL:"&&URLTmp
	SetRemoteClipboard URLTmp
	typetext controlkey,"v"	
	else if URLTmp contains "salesforce.lighthouse"
	replace "salesforce.lighthouse" in URLTmp with "test-salesforce.lighthouse"
	else
	Throw <<URL does not contain the string "awsgc".>>,"Script has been instructed to stop if this string is not found here."
		*)
	click "Environment_Refresh/Sandbox_Post_Refresh_Steps/06_WH_Hotline_For_Refresh/07_MPIE_Setup/AuthenticationProfile_Field"
	typetext "No"
	
	
	if ...
		... imagefound("Environment_Refresh/Sandbox_Post_Refresh_Steps/Navigation_Links/Logos/Summer_22_Logo"):
			set RepeatImageVar to "Environment_Refresh/Sandbox_Post_Refresh_Steps/04_Generic_Refresh_Steps/15_Named_Credentials_Manual_Masking/NewNamedCredential"
			set WaitImageVar to 8
			set DoURLFlip to True
		... imagefound("Environment_Refresh/Sandbox_Post_Refresh_Steps/Navigation_Links/Logos/Winter_23_Logo"):
			set RepeatImageVar to "Environment_Refresh/Sandbox_Post_Refresh_Steps/04_Generic_Refresh_Steps/15_Named_Credentials_Manual_Masking/NewNamedCredential" //"Environment_Refresh/Sandbox_Post_Refresh_Steps/06_WH_Hotline_For_Refresh/07_MPIE_Setup/BacktoNamedCredentials"
			set WaitImageVar to 20
			set DoURLFlip to False
		... imagefound("Environment_Refresh/Sandbox_Post_Refresh_Steps/Navigation_Links/Logos/Spring_23_Logo"):
			set RepeatImageVar to "Environment_Refresh/Sandbox_Post_Refresh_Steps/04_Generic_Refresh_Steps/15_Named_Credentials_Manual_Masking/NewNamedCredential" //"Environment_Refresh/Sandbox_Post_Refresh_Steps/06_WH_Hotline_For_Refresh/07_MPIE_Setup/BacktoNamedCredentials"
			set WaitImageVar to 20
			set DoURLFlip to False
		... imagefound("Environment_Refresh/Sandbox_Post_Refresh_Steps/Navigation_Links/Logos/Summer_23_Logo"):
			set RepeatImageVar to "Environment_Refresh/Sandbox_Post_Refresh_Steps/04_Generic_Refresh_Steps/15_Named_Credentials_Manual_Masking/NewNamedCredential" //"Environment_Refresh/Sandbox_Post_Refresh_Steps/06_WH_Hotline_For_Refresh/07_MPIE_Setup/BacktoNamedCredentials"
			set WaitImageVar to 20
			set DoURLFlip to False
		else
			throw "No logo recognized."
	end if
	
	repeat at least once until imagefound(image:RepeatImageVar, waitfor:WaitImageVar)
		click "Environment_Refresh/Sandbox_Post_Refresh_Steps/04_Generic_Refresh_Steps/09_Custom_Links/Save"
		click foundimagelocation()+[0,25]
	end repeat
	if DoURLFlip is True
		set the remoteclipboard to NamedCredURL
		put "Headed back to:"&&the remoteclipboard
		typetext controlkey, "lv"	
		typetext returnkey
	end if
	waitfor 9, "Environment_Refresh/Sandbox_Post_Refresh_Steps/Navigation_Links/Step_Headers/NamedCredentials"
	
	//Sometimes this page is not refreshing after a save.
	//this stuff all broke with the Winter '23 release
	(*
repeat at least once until imagefound(image:"Environment_Refresh/Sandbox_Post_Refresh_Steps/06_WH_Hotline_For_Refresh/07_MPIE_Setup/BacktoNamedCredentials", waitfor:12)
		click "Environment_Refresh/Sandbox_Post_Refresh_Steps/04_Generic_Refresh_Steps/09_Custom_Links/Save"
		click foundimagelocation()+[0,25]
	end repeat
	click foundimagelocation()
*)
	
	//Sometimes going back to Named Credentials it will throw out the selected view and it is necessary to select it again.
	Run "Utilities/CustomView".ChangeMyView SelectedView, DesiredView, ViewName
end repeat
Log "Completed editing Named Credential URLs." 
set the MultipleFoundAction to MultipleFoundState

write return&"Test run End:"&& the long date && the abbrev time & return & return to file Refresh_Report
close file Refresh_Report