
//We need to be in setup to do stuff
Run "Environment_Refresh/EnvRefresh_Helpers".Navigate_to_Setup "Lightning"

Put ResourcePath("Refresh_Reports\"&the suitevariables.SandboxName&"_Refresh_Report"&".csv") into Refresh_Report
open file Refresh_Report for appending 
write return&"Step 01 - Deliverability"&return to file Refresh_Report

//Searches Setup
Run "Environment_Refresh/EnvRefresh_Helpers".QuickFind "Deliverability", "Environment_Refresh/Sandbox_Post_Refresh_Steps/Navigation_Links/Lightning/Deliverability"
waitfor 12, "Common_Images/Mail_Icon"

click image:"Environment_Refresh/Sandbox_Post_Refresh_Steps/Non_VA_Main/01_Deliverability/Accesslevel",waitfor:9,hotspot:[120,8]
typetext "All email",returnkey

click "Environment_Refresh/Sandbox_Post_Refresh_Steps/10_MPIe_Post_Refresh_Steps/Save_New_Named_Credential"
waitfor 9, "Common_Images/Green_Check"

write "Access Level set to All Email." &return to file Refresh_Report

close file Refresh_Report